# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: OpenTelemetry collector
version: "0.0.1"
slug: otelcol
description: Bring the OpenTelemetry collector into your home
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
    exporters:
      otlp:
        endpoint: otelcol:4317
    extensions:
      health_check:
      pprof:
      zpages:
    service:
      extensions: [health_check,pprof,zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
schema:
  message: "str"
image: "ghcr.io/home-assistant/{arch}-addon-example"
